version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: abysshop-mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: ./backend
    container_name: abysshop-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SECRET_KEY: ${SECRET_KEY}
      INIT_VECTOR: ${INIT_VECTOR}
      IMAGE_DIR: ${IMAGE_DIR}
    ports:
      - ${SPRING_APP_PORT}:8080
    volumes:
      - /c/Users/Public/abysshop_img:/upload_img

  frontend:
    build: ./frontend
    container_name: abysshop-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"

volumes:
  mysql_data:
