export const POINT_RECHARGE_STATE = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_POINT_DEPOSIT: 'PENDING_POINT_DEPOSIT',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
};

export const POINT_RECHARGE_STATE_LABEL = {
  [POINT_RECHARGE_STATE.PENDING_PAYMENT]: '송금 확인 대기',
  [POINT_RECHARGE_STATE.PENDING_POINT_DEPOSIT]: '포인트 지급 대기',
  [POINT_RECHARGE_STATE.COMPLETED]: '포인트 지급 완료',
  [POINT_RECHARGE_STATE.REFUNDED]: '환불 처리 완료',
};
