server:
  port: 8081
  servlet:
    session:
      timeout: 60m

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: abysshop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/static/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true;
        show_sql: true;
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 30
        cache:
          use_second_level_cache: false
          use_query_cache: false

logging:
  level:
    org.springframework.security: DEBUG

