# Railway 배포 테스트 버전 application.yml
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations: file:${IMAGE_DIR:/upload_img}/

custom:
  encrypt:
    secret-key: ${SECRET_KEY}
    init-vector: ${INIT_VECTOR}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG

#배포 테스트용 admin 계정 정보
app:
  admin:
    username: testadmin
    password: superadmin
