server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  application:
    name: abysshop
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/static/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/**/*.xml
