server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  application:
    name: abysshop
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/static/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true;
        show_sql: true;
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 30
        cache:
          use_second_level_cache: true
          use_query_cache: true

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/**/*.xml
